name: LLVM Toolchain Install

on:
  push:
    branches: [main]

jobs:
  build:
    runs-opn: ubuntu-latest
    container:
      image: ghcr.io/pranav4330/cpullvmtoolchain22.x:ubuntu24.04

    steps:
      - uses: actions/checkout@v4
      - name: Eun ninja Install
        run: | 
          ninja llvm-Toolchain
          ninja install llvm-toolchain