# Copyright (c) 2025, Arm Limited and affiliates.
# Part of the Arm Toolchain project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ​​​​​Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# This workflow runs our alternative build configurations in parallel for multiple
# operating systems and architectures.
# It is intended to be triggered as part of a **nightly build** to
# validate these configurations and test them automatically.
# "Alternative" is meant loosely here--currently this mostly encompasses
# building various runtimes natively on non-x86_64 Linux targets.

name: Alternative Nightly Build and Test

on:
  workflow_dispatch:
  pull_request: # FIXME: remove, this is just for testing

permissions:
  contents: read

jobs:
  build-and-test:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: ${{ matrix.build_script }} on ${{ matrix.target_os }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # FIXME: once we are able to source an up-to-date qemu in a reasonable
          # way, this should be changed to just an ordinary build.
          - build_script: build_no_qemu.sh
            test_script: test.sh
            install_script: install_dependencies.sh
            target_os: Linux-AArch64
            runner: ubuntu-22.04-arm

          - build_script: build_musl-embedded_overlay.sh
            test_script: ''
            install_script: ''
            target_os: Linux-AArch64
            runner: ubuntu-22.04-arm

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # We build in the repository and rely on clean to cleanup possible
          # old build products if the runner doesn't do it itself.
          clean: true

      - name: Apply llvm-project patches
        run: python3 qualcomm-software/cmake/patch_repo.py --method apply qualcomm-software/patches/llvm-project

      - name: Build
        run: ./qualcomm-software/scripts/${{ matrix.build_script }}

      - name: Test
        if: matrix.test_script != ''
        run: ./qualcomm-software/scripts/${{ matrix.test_script }}

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: cpullvm-packages-${{ matrix.build_script }}-${{ matrix.target_os }}
          path: |
            build*/cpullvm-*.tar.xz
            build*/cpullvm-*.zip
          retention-days: 7
