# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Check whether a PR makes changes only in files that we are allowed
# to modify.

name: Check Modified Files

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-modified-files:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm

          - runner: ubuntu-22.04-arm

    steps:
      - name: Preconfigure git
        shell: bash
        run: |
          which clang++
          clang++ --version
          echo "int main() {}" > test.cpp
          clang++ -stdlib=libc++ -fuse-ld=lld test.cpp
