# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Check whether a PR makes changes only in files that we are allowed
# to modify.

name: Check Modified Files

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-modified-files:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    runs-on: cpullvm-ubuntu24-x86_64

    steps:
      - name: Check qemu
        run: |
          which qemu-system-riscv32
          qemu-system-riscv32 --version

  check-modified-files2:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    runs-on: self-hosted

    steps:
      - name: Check qemu
        run: |
          which qemu-system-riscv32
          qemu-system-riscv32 --version