name: Nightly-Linux-AArch64

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-nightly-aarch64-linux]

  schedule:
    - cron: '0 5 * * *' # 9 PM PT (UTC)

jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      runner: ubuntu-22.04-arm
      build-script: "src/qualcomm-software/embedded/scripts/build.sh"
      is-nightly: true
      arch: AArch64
