name: Nightly-Linux-x86_64

on:
  repository_dispatch:
    types: [trigger-nightly-x86-linux]

  schedule:
    - cron: '0 5 * * *' # 9 PM PT (UTC)

jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      build-script: "src/qualcomm-software/embedded/scripts/build.sh --nightly"
      is-nightly: true
      arch: x86_64
