name: Nightly-aarch64

on:
  repository_dispatch:
    types: [trigger-nightly-aarch64]

  schedule:
    - cron: '0 5 * * *' # 9 PM PT (UTC)

jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      build-script: "src/qualcomm-software/embedded/scripts/build.sh"
      is-nightly: true
      arch: aarch64
