name: nightly

on:
  schedule:
    - cron: '0 5 * * *' # 9 PM PT (UTC)

jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      build-script: "src/qualcomm-software/embedded/scripts/build.sh --artifact-dir /local/mnt/workspace/nightly-toolchain/${{ github.ref_name }}"
