# Copyright (c) 2025, Arm Limited and affiliates.
# Part of the Arm Toolchain project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ​​​​​Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# This workflow runs our common build scripts in parallel for Linux x86_64 and
# Windows x86_64.
#
# It is intended to be triggered as part of a **nightly build** to validate our
# typical build configurations and test them automatically.

name: Nightly Build and Test

on:
  workflow_dispatch:
    inputs:
      enable_assertions:
        description: 'Enable LLVM assertions'
        type: boolean
        default: true
  workflow_call:
    inputs:
      enable_assertions:
        description: 'Enable LLVM assertions'
        type: boolean
        default: true
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
    - cron: '0 7,19 * * *' # 12 AM, 12 PM PT
permissions:
  contents: read

env:
  EXTRA_CMAKE_ARGS: ${{ format('{0}', inputs.enable_assertions) == 'false' && '-DLLVM_ENABLE_ASSERTIONS=OFF' || '-DLLVM_ENABLE_ASSERTIONS=ON' }}

jobs:
  build-and-test-Linux-x86:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: build.sh on Linux-x86_64
    runs-on: cpullvm-ubuntu24-x86_64
    steps:
      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # We build in the repository and rely on clean to cleanup possible
          # old build products if the runner doesn't do it itself.
          clean: true

      - name: Apply llvm-project patches
        run: python3 qualcomm-software/cmake/patch_repo.py --method apply qualcomm-software/patches/llvm-project

      - name: Build
        run: ./qualcomm-software/scripts/build.sh

      - name: Upload built packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: success()
        with:
          name: cpullvm-packages-build.sh-Linux-x86
          path: build*/cpullvm-*.tar.xz
          if-no-files-found: error
          retention-days: 7

      - name: Test
        run: ./qualcomm-software/scripts/test.sh

  build-Windows-x86:
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: build.ps1 on Windows-x86_64
    runs-on: windows-2025
    steps:
      - name: Preconfigure git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.longpaths true

      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # We build in the repository and rely on clean to cleanup possible
          # old build products if the runner doesn't do it itself.
          clean: true

      - name: Install dependencies
        run: ./qualcomm-software/scripts/install_dependencies.ps1

      - name: Apply llvm-project patches
        run: python3 qualcomm-software/cmake/patch_repo.py --method apply qualcomm-software/patches/llvm-project

      - name: Build
        run: ./qualcomm-software/scripts/build.ps1

      - name: Upload built packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: success()
        with:
          name: cpullvm-packages-build.ps1-Windows-x86
          path: |
            build*/cpullvm-*.zip
            !build/cpullvm-*-Linux-x86_64*.tar.xz
          retention-days: 7
