# Copyright (c) 2025, Arm Limited and affiliates.
# Part of the Arm Toolchain project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ​​​​​Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# This workflow runs all build scripts in parallel for multiple operating
# systems and architectures.
# It is intended to be triggered as part of a **nightly build** to
# validate all build configurations and test them automatically.

name: Nightly Build and Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: ${{ matrix.build_script }} on ${{ matrix.target_os }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build_script: build.sh
            test_script: test.sh
            target_os: Linux-x86_64
            runner: self-hosted

          - build_script: build_no_runtimes.sh
            test_script: test_no_runtimes.sh
            target_os: Linux-AArch64
            runner: ubuntu-22.04-arm

          - build_script: build_musl-embedded_overlay.sh
            test_script: ''
            target_os: Linux-x86_64
            runner: self-hosted

          - build_script: build.ps1
            test_script: test.ps1
            target_os: Windows-x86_64
            runner: windows-latest

          - build_script: build.ps1
            test_script: test.ps1
            target_os: Windows-AArch64
            runner: windows-11-arm

    steps:
      # Not setting these can cause lit test failures on Windows machines when
      # files with ex: different line endings are compared.
      - name: Preconfigure git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.longpaths true

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # We build in the repository and rely on clean to cleanup possible
          # old build products if the runner doesn't do it itself.
          clean: true

      - name: Apply llvm-project patches
        run: python3 qualcomm-software/cmake/patch_repo.py --method apply qualcomm-software/patches/llvm-project

      # Needed for eld tests.
      # If there are more dependencies, add an install script.
      - name: Install PyYAML (Windows)
        if: runner.os == 'Windows'
        run: pip install pyyaml

      - name: Build
        run: ./qualcomm-software/scripts/${{ matrix.build_script }}

      - name: Test
        if: matrix.test_script != ''
        run: ./qualcomm-software/scripts/${{ matrix.test_script }}

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: cpullvm-packages-${{ matrix.build_script }}-${{ matrix.target_os }}
          path: |
            build*/cpullvm-*.tar.xz
            build*/cpullvm-*.zip
          retention-days: 7
