name: pre-checkin-aarch64

on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # 9 PM PT

jobs:
  build:
    runs-on: self-hosted
    concurrency:
      group: "${{ github.workflow }}-${{ github.event.pull_request.number || 'nightly' }}"
      cancel-in-progress: true
    permissions:
      contents: write
      statuses: write

    env:
      SRC_DIR: "${{ github.workspace }}/src"
      BUILD_DIR: "${{ github.workspace }}/build"
      INSTALL_DIR: "${{ github.workspace }}/install"
      BUILD_DIR_AARCH64: "${{ github.workspace }}/build/aarch64"
      INSTALL_DIR_AARCH64: "${{ github.workspace }}/install/aarch64"
      CCACHE_DIR: "/local/mnt/workspace/cpullvm_ccache/${{ github.event.pull_request.base.ref || 'nightly' }}"
      CCACHE_BASEDIR: "${{ github.workspace }}/pr-${{ github.event.number || 'nightly' }}"
      BUILD_MODE: "Release"
      ASSERTION_MODE: "OFF"
      ARM32_LINUX_TRIPLE: "arm-linux-gnueabi"
      AARCH64_LINUX_TRIPLE: "aarch64-linux-gnu"
      COMPILER_RT_ARM32_LINUX_BUILDDIR: "${{ github.workspace }}/build/compiler-rt/arm32/linux"
      COMPILER_RT_AARCH64_LINUX_BUILDDIR: "${{ github.workspace }}/build/compiler-rt/aarch64/linux"
      COMPILER_RT_ARM32_LINUX_FLAGS: "--target=arm-linux-gnueabi -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=neon"
      COMPILER_RT_AARCH64_LINUX_FLAGS: "--sysroot=/usr/aarch64-linux-gnu --target=aarch64-linux-gnu -mcpu=cortex-a53"
      ARM32_BM_TRIPLE: "arm-none-eabi"
      AARCH64_BM_TRIPLE: "aarch64-none-elf"
      COMPILER_RT_ARM32_BM_BUILDDIR: "${{ github.workspace }}/build/compiler-rt/arm32/baremetal"
      COMPILER_RT_AARCH64_BM_BUILDDIR: "${{ github.workspace }}/build/compiler-rt/aarch64/baremetal"
      COMPILER_RT_ARM32_BM_FLAGS: "--target=arm-none-eabi -mcpu=cortex-a9 -ffunction-sections -fdata-sections -mfloat-abi=softfp -mfpu=neon -nostdlibinc"
      COMPILER_RT_AARCH64_BM_FLAGS: "--target=aarch64-none-elf -mcpu=cortex-a53 -ffunction-sections -fdata-sections -nostdlibinc"
      AARCH64_LIBC: "/usr/aarch64-none-linux-gnu/libc"
      AARCH64_LINUX_FLAGS: "--target=aarch64-linux-gnu --sysroot=/usr/aarch64-none-linux-gnu/libc --gcc-toolchain=/usr -pthread"
      RPATH_LINK_FLAGS: "-Wl,-rpath-link,/usr/aarch64-none-linux-gnu/libc/lib -Wl,-rpath-link,/usr/aarch64-none-linux-gnu/libc/usr/lib -Wl,-rpath-link,/usr/aarch64-none-linux-gnu/libc/lib64 -Wl,-rpath-link,/usr/aarch64-none-linux-gnu/libc/usr/lib64 -L/usr/aarch64-none-linux-gnu/libc/lib -L/usr/aarch64-none-linux-gnu/libc/usr/lib -L/usr/aarch64-none-linux-gnu/libc/lib64 -L/usr/aarch64-none-linux-gnu/libc/usr/lib64"

    steps:
      - name: Workspace Cleanup
        shell: bash
        run: |
          echo "Clean workspace dir..."
          rm -rf "${{ github.workspace }}"/*

      - name: Create source root
        shell: bash
        run: mkdir -p "${SRC_DIR}"

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || 'qualcomm/cpullvm-toolchain' }}
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          path: ${{ env.SRC_DIR }}/llvm-top
          fetch-depth: 0

      - name: Fetch musl-embedded
        uses: actions/checkout@v4
        with:
          repository: qualcomm/musl-embedded
          path: ${{ env.SRC_DIR }}/musl-embedded

      - name: Fetch qualcomm/eld
        uses: actions/checkout@v4
        with:
          repository: qualcomm/eld
          path: ${{ env.SRC_DIR }}/llvm-top/llvm/tools/eld
          ref: 65ea860802c41ef5c0becff9750a350495de27b0

      - name: Apply patches
        shell: bash
        run: |
          python3 "${SRC_DIR}/llvm-top/qualcomm-software/embedded/tools/patchctl.py" apply -f "${SRC_DIR}/llvm-top/qualcomm-software/embedded/patchsets.yml"

      - name: Build and Test
        shell: bash
        run: |
          ${SRC_DIR}/llvm-top/qualcomm-software/embedded/scripts/build_aarch64.sh --skip-clones --aarch64-build