name: pre-checkin

on:
  pull_request:
    paths-ignore:
      - 'qualcomm-software/embedded/scripts/build.ps1'
      - '.github/workflows/nightly-win-x86.yml'
      - '.github/workflows/nightly-woa.yml'


jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      runner: self-hosted
      build-script: "src/qualcomm-software/embedded/scripts/build.sh"
