name: pre-checkin

on:
  pull_request:
    paths-ignore:
      - 'qualcomm-software/embedded/scripts/build.bat'
      - '.github/workflows/pre-checkin-win.yml'

jobs:
  base:
    uses: ./.github/workflows/base-build.yml
    with:
      build-script: "src/qualcomm-software/embedded/scripts/build.sh"
