name: pre-checkin

on:
  pull_request:

jobs:
  call-base:
    uses: ./.github/workflows/base-build.yml
    with:
      build-script: "${SRC_DIR}/llvm-top/qualcomm-software/embedded/scripts/build.sh"
      checkout-ref: ${{ github.event.pull_request.head.ref }}
      checkout-repo: ${{ github.event.pull_request.head.repo.full_name }}
