name: pre-checkin-win-x86_64

on:
  pull_request: #this needs to be removed before merging.
    paths-ignore:
      - 'qualcomm-software/embedded/scripts/build.sh'
      - '.github/workflows/pre-checkin.yml'
      - '.github/workflows/pre-checkin-aarch64.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: Disable Git auto CRLF conversion
        run: git config --global core.autocrlf false

      - name: Configure Git for patch application
        working-directory: src
        shell: cmd
        run: >
          git config --local user.name "Qualcomm CI" &&
          git config --local user.email "ci@qti.qualcomm.com" &&
          git config --local core.autocrlf false &&
          git config --local core.safecrlf true

      - name: Build
        working-directory: src
        shell: cmd
        env:
          GIT_AUTHOR_NAME: Qualcomm CI
          GIT_AUTHOR_EMAIL: ci@qti.qualcomm.com
          GIT_COMMITTER_NAME: Qualcomm CI
          GIT_COMMITTER_EMAIL: ci@qti.qualcomm.com
        run: >
          .\qualcomm-software\embedded\scripts\build.bat
