name: Running cpullvm-toolchain Image

on:
  workflow_dispatch:

jobs:
  pull_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run LLVM toolchain build inside container
        run: |
          docker run --rm ghcr.io/pranav4330/cpullvmtoolchain22.x:ubuntu24.04 \
            bash -c "ninja llvm-toolchain && ninja install llvm-toolchain"